#!/usr/bin/env bash
#
# One-command installer for the Lead Distribution CRM.
#
#   curl -fsSL https://raw.githubusercontent.com/tamerx97/Lead-Gen-SYS/main/install.sh | sudo bash
#
# It installs Docker if needed, generates your passwords, starts everything,
# creates your login, and prints the details. Re-running it is safe.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/tamerx97/Lead-Gen-SYS.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/leadgen}"
COMPOSE_FILE="docker-compose.prod.yml"

bold=$'\033[1m'; green=$'\033[32m'; yellow=$'\033[33m'; red=$'\033[31m'; dim=$'\033[2m'; reset=$'\033[0m'

say()  { printf '%s\n' "$*"; }
step() { printf '\n%s==>%s %s%s\n' "$green" "$reset" "$bold" "$*$reset"; }
warn() { printf '%s!%s  %s\n' "$yellow" "$reset" "$*"; }
die()  { printf '\n%sX  %s%s\n\n' "$red" "$*" "$reset" >&2; exit 1; }

# ---------------------------------------------------------------- preflight
[ "$(id -u)" -eq 0 ] || die "Please run this with sudo:  curl -fsSL <url> | sudo bash"

command -v curl >/dev/null 2>&1 || die "curl is required but not installed."

# ------------------------------------------------------------------ inputs
# Accept answers as arguments or environment variables so the script can also
# run unattended:  sudo bash install.sh leads.example.com you@example.com
APP_DOMAIN="${1:-${APP_DOMAIN:-}}"
ADMIN_EMAIL="${2:-${ADMIN_EMAIL:-}}"

if [ -z "$APP_DOMAIN" ]; then
  step "Your web address"
  say "${dim}The domain you'll use to open the dashboard, e.g. leads.yourcompany.com${reset}"
  say "${dim}It must already point at this server. Leave blank to use this server's IP address.${reset}"
  printf 'Domain: '
  read -r APP_DOMAIN </dev/tty || true
fi

USE_TLS=true
if [ -z "$APP_DOMAIN" ]; then
  # No domain: fall back to the raw IP over plain HTTP. Certificates cannot be
  # issued for a bare IP, so HTTPS is not possible in this mode.
  APP_DOMAIN="$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"
  USE_TLS=false
  warn "No domain given — using http://$APP_DOMAIN (no HTTPS)."
  warn "Traffic will not be encrypted. Add a domain later and re-run this script to enable HTTPS."
fi

if [ -z "$ADMIN_EMAIL" ]; then
  step "Your login email"
  printf 'Email: '
  read -r ADMIN_EMAIL </dev/tty || true
fi
[ -n "$ADMIN_EMAIL" ] || die "An email address is required — it's your username for the dashboard."
case "$ADMIN_EMAIL" in *@*.*) ;; *) die "\"$ADMIN_EMAIL\" doesn't look like an email address." ;; esac

step "Checking for Docker"
if ! command -v docker >/dev/null 2>&1; then
  say "Docker isn't installed. Installing it now (this takes a minute)…"
  curl -fsSL https://get.docker.com | sh >/dev/null 2>&1 \
    || die "Docker installation failed. Install Docker manually, then re-run this script."
  say "Docker installed."
else
  say "Docker is already installed."
fi

# Compose v2 ships with modern Docker as a plugin.
docker compose version >/dev/null 2>&1 \
  || die "Your Docker is too old — it lacks 'docker compose'. Upgrade Docker, then re-run."

systemctl start docker >/dev/null 2>&1 || true
docker info >/dev/null 2>&1 || die "Docker is installed but not running. Start it with: systemctl start docker"

# ------------------------------------------------------------------- fetch
step "Getting the software"
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Already installed at $INSTALL_DIR — updating to the latest version."
  git -C "$INSTALL_DIR" fetch --quiet origin main
  git -C "$INSTALL_DIR" reset --hard --quiet origin/main
else
  command -v git >/dev/null 2>&1 || {
    (apt-get update -qq && apt-get install -y -qq git) >/dev/null 2>&1 \
      || (yum install -y -q git) >/dev/null 2>&1 \
      || die "git is required but could not be installed automatically."
  }
  rm -rf "$INSTALL_DIR"
  git clone --quiet --depth 1 "$REPO_URL" "$INSTALL_DIR" \
    || die "Could not download the software from $REPO_URL"
fi
cd "$INSTALL_DIR"

# --------------------------------------------------------------- configure
step "Setting up your configuration"
ADMIN_PASSWORD=""
if [ -f .env ]; then
  say "Keeping your existing settings and passwords (.env already exists)."
  # shellcheck disable=SC1091
  APP_DOMAIN="$(grep -E '^APP_DOMAIN=' .env | cut -d= -f2- || echo "$APP_DOMAIN")"
else
  POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '\n/+=' | cut -c1-32)"
  JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '\n/+=' | cut -c1-20)"

  cat > .env <<ENVEOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file secret — it contains your passwords.
APP_DOMAIN=$APP_DOMAIN
POSTGRES_USER=leadgen
POSTGRES_DB=leadgen
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=600
DELIVERY_TIMEOUT_MS=8000
DELIVERY_MAX_ATTEMPTS=3
DELIVERY_BACKOFF_MS=500
LOG_LEVEL=info
ENVEOF
  chmod 600 .env
  say "Generated new passwords and saved them to $INSTALL_DIR/.env"
fi

# Without a domain there is no certificate to issue, so serve plain HTTP.
if [ "$USE_TLS" = false ]; then
  cat > Caddyfile <<'CADDYEOF'
# No domain configured, so this serves plain HTTP on port 80.
# Re-run install.sh with a domain to get automatic HTTPS.
:80 {
	encode gzip
	reverse_proxy app:4000
	header {
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		-Server
	}
	log {
		output stdout
		format console
	}
}
CADDYEOF
fi

# ----------------------------------------------------------------- launch
step "Building and starting (first run takes a few minutes)"
docker compose -f "$COMPOSE_FILE" up -d --build \
  || die "Startup failed. See what went wrong with:  cd $INSTALL_DIR && docker compose -f $COMPOSE_FILE logs"

step "Waiting for the system to come up"
healthy=false
for i in $(seq 1 90); do
  if docker compose -f "$COMPOSE_FILE" exec -T app \
       node -e "fetch('http://127.0.0.1:4000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
       >/dev/null 2>&1; then
    healthy=true
    say "Up and running after ${i}s."
    break
  fi
  sleep 1
done

if [ "$healthy" = false ]; then
  docker compose -f "$COMPOSE_FILE" logs --tail 40 app || true
  die "The system did not start. The logs above should say why."
fi

# ------------------------------------------------------------------ admin
step "Creating your login"
if [ -n "$ADMIN_PASSWORD" ]; then
  docker compose -f "$COMPOSE_FILE" exec -T app \
    node api/dist/src/scripts/createAdmin.js "$ADMIN_EMAIL" "$ADMIN_PASSWORD" \
    || die "Could not create your login."
else
  say "${dim}An existing installation was found, so your current password is unchanged.${reset}"
fi

# ----------------------------------------------------------------- report
scheme="https"; [ "$USE_TLS" = false ] && scheme="http"
URL="$scheme://$APP_DOMAIN"

line="────────────────────────────────────────────────────────────────────"
printf '\n%s%s%s\n' "$green" "$line" "$reset"
printf '%s  YOUR LEAD SYSTEM IS LIVE%s\n' "$bold" "$reset"
printf '%s%s%s\n\n' "$green" "$line" "$reset"
printf '  Open this in your browser:\n'
printf '    %s%s%s\n\n' "$bold" "$URL" "$reset"
printf '  Sign in with:\n'
printf '    Email:     %s\n' "$ADMIN_EMAIL"
if [ -n "$ADMIN_PASSWORD" ]; then
  printf '    Password:  %s%s%s\n\n' "$bold" "$ADMIN_PASSWORD" "$reset"
  printf '  %sWrite this password down now — it is not shown again.%s\n' "$yellow" "$reset"
  printf '  (You can change it later from inside the dashboard.)\n\n'
else
  printf '    Password:  (unchanged from your previous install)\n\n'
fi
if [ "$USE_TLS" = true ]; then
  printf '  %sIf the page does not load yet, wait 1-2 minutes:%s the security\n' "$dim" "$reset"
  printf '  certificate is still being issued. This only happens once.\n\n'
fi
printf '  %sUseful commands%s (run them inside %s):\n' "$bold" "$reset" "$INSTALL_DIR"
printf '    See what it is doing:  docker compose -f %s logs -f\n' "$COMPOSE_FILE"
printf '    Stop it:               docker compose -f %s down\n' "$COMPOSE_FILE"
printf '    Start it again:        docker compose -f %s up -d\n' "$COMPOSE_FILE"
printf '    Update to latest:      sudo bash install.sh\n'
printf '\n%s%s%s\n\n' "$green" "$line" "$reset"
